In [53]:
import numpy as np

In [5]:
a = np.zeros(5) #Return a new array of given shape and type, filled with zeros.

In [6]:
a.ndim

1

In [7]:
b = np.zeros((3, 4))

In [8]:
b.ndim

2

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.twos(5)

AttributeError: module 'numpy' has no attribute 'twos'

In [13]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [15]:
arr = np.zeros((3,4))

In [16]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
arr.ndim

2

In [20]:
# 3 dimensional array
np.zeros(1)

array([0.])

In [21]:
np.zeros((2,3)).ndim

2

In [22]:
arr = np.zeros((3,4))
arr.ndim

2

In [23]:
arr = np.zeros((1,3,4))

In [24]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [25]:
arr.ndim

3

In [26]:
arr = np.zeros((1,1,3,4))

In [27]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [28]:
arr.ndim

4

In [29]:
arr = np.ones((3,4))

In [30]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
arr.shape

(3, 4)

In [33]:
a = arr + 5

In [34]:
a -1

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [35]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3, dtype= int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [39]:
np.empty((3, 4)) #Return a new array of given shape and type, without initializing entries

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [54]:
#optional >> random module

import random
random.choice((1,2,3,4,5))

1

In [45]:
random.choice('Bhavika')

'a'

In [47]:
random.randrange(1,10)

7

In [ ]:
random.random() # a random no is generated between 0(included) and 1(excluded)

0.09984958746337136

In [49]:
lis = [1,2,3,45,5]
lis

[1, 2, 3, 45, 5]

In [50]:
random.shuffle(lis)

In [51]:
lis

[1, 45, 2, 3, 5]

In [55]:
random.uniform(7, 18)

17.55865849378786

In [57]:
# random number related concept in numpy
np.array([])

array([], dtype=float64)

In [58]:
np.random.random_sample()

0.7018683407746135

In [60]:
np.random.random_sample((5, ))

array([0.83550836, 0.70876758, 0.93172838, 0.37928923, 0.07943809])

In [61]:
np.random.rand(1)

array([0.82990469])

In [62]:
np.random.rand(2, 3)

array([[0.65497105, 0.39918509, 0.81321891],
       [0.11520469, 0.69288286, 0.21297674]])

In [63]:
np.random.randn(2, 3)

array([[-0.56028168,  0.42251494, -0.01851871],
       [ 0.19406916, -1.27087101,  0.19337524]])

In [65]:
arr = np.random.randint(1, 5, size=(3,4))

In [66]:
arr

array([[2, 4, 4, 1],
       [4, 3, 1, 3],
       [4, 3, 1, 1]])

In [67]:
arr.ndim

2

In [68]:
arr.shape

(3, 4)

In [69]:
arr.size

12

In [70]:
# reshaping the array

arr1 = arr.reshape(2, 6)

In [71]:
arr1.shape

(2, 6)

In [72]:
arr1

array([[2, 4, 4, 1, 4, 3],
       [1, 3, 4, 3, 1, 1]])

In [73]:
arr.size

12

In [74]:
arr

array([[2, 4, 4, 1],
       [4, 3, 1, 3],
       [4, 3, 1, 1]])

In [75]:
arr1.size

12

In [76]:
# array size will not change , always resape parameter should be multiplication of original array size
arr

array([[2, 4, 4, 1],
       [4, 3, 1, 3],
       [4, 3, 1, 1]])

In [77]:
arr.size

12

In [78]:
arr.reshape(12,1)

array([[2],
       [4],
       [4],
       [1],
       [4],
       [3],
       [1],
       [3],
       [4],
       [3],
       [1],
       [1]])

In [79]:
arr.reshape(1, 12)

array([[2, 4, 4, 1, 4, 3, 1, 3, 4, 3, 1, 1]])

In [80]:
arr.reshape(3,4)

array([[2, 4, 4, 1],
       [4, 3, 1, 3],
       [4, 3, 1, 1]])

In [ ]:
arr.reshape(1,2) # multiplication must be equal to size (3*4 = 12 but 1*2 != 12)

ValueError: cannot reshape array of size 12 into shape (1,2)

In [87]:
# case when you dont know in reshape what should be the colume count 

arr.reshape(4,-1) 

array([[2, 4, 4],
       [1, 4, 3],
       [1, 3, 4],
       [3, 1, 1]])

In [85]:
arr.reshape(2,-1)

array([[2, 4, 4, 1, 4, 3],
       [1, 3, 4, 3, 1, 1]])

In [ ]:
arr.reshape(3, -100) # 3 is your rows and -100 only divide them in rows

array([[2, 4, 4, 1],
       [4, 3, 1, 3],
       [4, 3, 1, 1]])

In [90]:
arr2 = arr.reshape(-1, 4) # you colume count nut not row count

In [91]:
arr2.size

12

In [92]:
arr.reshape(12,1)

array([[2],
       [4],
       [4],
       [1],
       [4],
       [3],
       [1],
       [3],
       [4],
       [3],
       [1],
       [1]])

In [ ]:
arr.reshape(12,1).base # to see the original array

array([[2, 4, 4, 1],
       [4, 3, 1, 3],
       [4, 3, 1, 1]])

In [97]:
arr.reshape(2,2,3)

array([[[2, 4, 4],
        [1, 4, 3]],

       [[1, 3, 4],
        [3, 1, 1]]])

In [99]:
arr.reshape(3,2,2)

array([[[2, 4],
        [4, 1]],

       [[4, 3],
        [1, 3]],

       [[4, 3],
        [1, 1]]])

In [102]:
arr.reshape(1,2,2,3)

array([[[[2, 4, 4],
         [1, 4, 3]],

        [[1, 3, 4],
         [3, 1, 1]]]])

In [101]:
arr.reshape(3,2,2,1)

array([[[[2],
         [4]],

        [[4],
         [1]]],


       [[[4],
         [3]],

        [[1],
         [3]]],


       [[[4],
         [3]],

        [[1],
         [1]]]])

In [103]:
arr.reshape(3,2,2,1).ndim

4

In [ ]:
arr.reshape(4,3,1) # 3 rows , 1 column repeated 4 times in the third dimension 

array([[[2],
        [4],
        [4]],

       [[1],
        [4],
        [3]],

       [[1],
        [3],
        [4]],

       [[3],
        [1],
        [1]]])

In [105]:
# condition on array 

arr1 = np.random.randint(1, 10, (5,6))

In [106]:
arr1

array([[7, 2, 9, 9, 5, 3],
       [6, 8, 2, 6, 2, 2],
       [7, 6, 3, 9, 6, 9],
       [5, 1, 3, 9, 3, 3],
       [2, 8, 2, 6, 2, 2]])

In [107]:
arr1.shape

(5, 6)

In [108]:
arr1.ndim

2

In [109]:
arr1.size

30

In [110]:
arr1 > 3

array([[ True, False,  True,  True,  True, False],
       [ True,  True, False,  True, False, False],
       [ True,  True, False,  True,  True,  True],
       [ True, False, False,  True, False, False],
       [False,  True, False,  True, False, False]])

In [112]:
arr1[arr1 > 3]

array([7, 9, 9, 5, 6, 8, 6, 7, 6, 9, 6, 9, 5, 9, 8, 6])

In [ ]:
arr1[arr1 < 3]

In [116]:
arr1

array([[7, 2, 9, 9, 5, 3],
       [6, 8, 2, 6, 2, 2],
       [7, 6, 3, 9, 6, 9],
       [5, 1, 3, 9, 3, 3],
       [2, 8, 2, 6, 2, 2]])

In [ ]:
# to access elements in the array
arr1[0]

array([7, 2, 9, 9, 5, 3])

In [115]:
arr1[1]

array([6, 8, 2, 6, 2, 2])

In [117]:
arr1[1][0]

np.int64(6)

In [ ]:
arr1[0:3] # 0th row , 1st row, 2nd row

array([[7, 2, 9, 9, 5, 3],
       [6, 8, 2, 6, 2, 2],
       [7, 6, 3, 9, 6, 9]])

In [119]:
arr1[0:3, [0,2]]  # 0th and 2nd column

array([[7, 9],
       [6, 2],
       [7, 3]])

In [126]:
arr1

array([[7, 2, 9, 9, 5, 3],
       [6, 8, 2, 6, 2, 2],
       [7, 6, 3, 9, 6, 9],
       [5, 1, 3, 9, 3, 3],
       [2, 8, 2, 6, 2, 2]])

In [130]:
arr1[0:3, 1:3]

array([[2, 9],
       [8, 2],
       [6, 3]])

In [124]:
arr1[0, [1,3]]

array([2, 9])

In [ ]:
arr1[2:4, [0,3]]

array([[7, 9],
       [5, 9],
       [2, 6]])

In [ ]:
# mathematical operation on two arrays
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [132]:
arr1

array([[2, 1, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [133]:
arr2

array([[2, 1, 1],
       [2, 2, 2],
       [1, 2, 1]])

In [ ]:
arr1+arr2 # index wise addition

array([[4, 2, 2],
       [3, 4, 4],
       [2, 4, 2]])

In [ ]:
arr1*arr2 # index wise multiplication

array([[4, 1, 1],
       [2, 4, 4],
       [1, 4, 1]])

In [ ]:
arr1-arr2 # index wise subtraction

array([[ 0,  0,  0],
       [-1,  0,  0],
       [ 0,  0,  0]])

In [ ]:
arr1 / arr2 # index wise divison

array([[1. , 1. , 1. ],
       [0.5, 1. , 1. ],
       [1. , 1. , 1. ]])

In [140]:
4/0

ZeroDivisionError: division by zero

In [ ]:
arr1/0 # in phython zero divion show error, but in numpy no error

/var/folders/br/l24p9wqx0ml2rhgy4bgyvl9w0000gn/T/ipykernel_2131/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
# matrix multiplication >> different from index wise multiplication

arr1 @ arr2  # 1st way to do matrix multiplication

# it will when no. of column of arr1 and no. of row of arr2 is equal(-:|:- n = p)

array([[7, 6, 5],
       [8, 9, 7],
       [7, 7, 6]])

In [ ]:
np.dot(arr1,arr2) # 2st way to do matrix multiplication

array([[7, 6, 5],
       [8, 9, 7],
       [7, 7, 6]])

In [147]:
arr = np.zeros([3,3])

In [158]:
# broadcasting
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [159]:
arr+5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [160]:
a = np.array([1,2,3])

In [161]:
a.ndim

1

In [162]:
a

array([1, 2, 3])

In [163]:
arr + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
a = np.array([1,2,3,4])

In [165]:
a

array([1, 2, 3, 4])

In [ ]:
#Transpose
a.T

array([1, 2, 3, 4])

In [167]:
a = np.array([[1,2,3,4]])

In [168]:
a.T

array([[1],
       [2],
       [3],
       [4]])

In [169]:
arr1

array([[2, 1, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [170]:
arr1.T

array([[2, 1, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [171]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.        ],
       [1.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        ]])

In [172]:
np.square(arr1)

array([[4, 1, 1],
       [1, 4, 4],
       [1, 4, 1]])

In [173]:
np.log10(arr1)

array([[0.30103, 0.     , 0.     ],
       [0.     , 0.30103, 0.30103],
       [0.     , 0.30103, 0.     ]])

In [174]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183]])

In [175]:
np.min(arr1)

np.int64(1)

In [176]:
np.max(arr1)

np.int64(2)