In [ ]:
# Numpy >> numerical python
#2005 by travis Oliphant 

In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
lis = [1,2,"Raghav",3+4j,1.2,True]

In [5]:
type(lis)

list

In [6]:
lis

[1, 2, 'Raghav', (3+4j), 1.2, True]

In [7]:
# Numpy store the data in an array
# An array is a container used to store the data of same data type

In [8]:
# why numpy
# computation is fast >> due to array >> continous memory location
# mathematical computaion

In [15]:
l = [1,2,3,4,5]
arr = np.array(l)

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
l = [1,2,3,4,5.2]
arr = np.array(l)

In [ ]:
arr 

array([1. , 2. , 3. , 4. , 5.2])

In [19]:
l = [1,2,3,4,5.2,"KK"]
arr = np.array(l)

In [20]:
arr

array(['1', '2', '3', '4', '5.2', 'KK'], dtype='<U32')

In [21]:
# arr stores homogenous data

In [22]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim # dimension of array

1

In [24]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [25]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr1.ndim

2

In [27]:
mat = np.matrix([1,2,3]) # matrix is a specialised array, 2 dimensional

In [28]:
type(mat)

numpy.matrix

In [29]:
np.matrix([[[1,2],[3,4],[5,6]]])

ValueError: matrix must be 2-dimensional

In [ ]:
# more way to convert array
l = [1,2,3,4]
np.asarray(l)

array([1, 2, 3, 4])

In [31]:
mat

matrix([[1, 2, 3]])

In [32]:
np.asarray(mat)

array([[1, 2, 3]])

In [33]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
np.asanyarray(mat) # it only convert those subclass into array which is not in array, but if something is already in it do not do any thing.

matrix([[1, 2, 3]])