In [1]:
import numpy as np

In [5]:
a = np.zeros(5) #Return a new array of given shape and type, filled with zeros.

In [6]:
a.ndim

1

In [7]:
b = np.zeros((3, 4))

In [8]:
b.ndim

2

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.twos(5)

AttributeError: module 'numpy' has no attribute 'twos'

In [13]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [15]:
arr = np.zeros((3,4))

In [16]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
arr.ndim

2

In [20]:
# 3 dimensional array
np.zeros(1)

array([0.])

In [21]:
np.zeros((2,3)).ndim

2

In [22]:
arr = np.zeros((3,4))
arr.ndim

2

In [23]:
arr = np.zeros((1,3,4))

In [24]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [25]:
arr.ndim

3

In [26]:
arr = np.zeros((1,1,3,4))

In [27]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [28]:
arr.ndim

4

In [29]:
arr = np.ones((3,4))

In [30]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
arr.shape

(3, 4)

In [33]:
a = arr + 5

In [34]:
a -1

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [35]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3, dtype= int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [39]:
np.empty((3, 4)) #Return a new array of given shape and type, without initializing entries

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
#optional >> random module

import random
random.choice((1,2,3,4,5))

1

In [45]:
random.choice('Bhavika')

'a'

In [47]:
random.randrange(1,10)

7

In [ ]:
random.random() # a random no is generated between 0(included) and 1(excluded)

0.09984958746337136

In [49]:
lis = [1,2,3,45,5]
lis

[1, 2, 3, 45, 5]

In [50]:
random.shuffle(lis)

In [51]:
lis

[1, 45, 2, 3, 5]

In [52]:
random.uniform(7, 18)

15.142954545718405