In [1]:
import numpy as np

In [39]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [3]:
arr1

array([[2, 1, 1],
       [2, 2, 1],
       [1, 2, 2]])

In [4]:
arr1.flatten() # return a copy of the array collapsed into one direction 

array([2, 1, 1, 2, 2, 1, 1, 2, 2])

In [5]:
# expand dimension
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
arr.ndim

1

In [ ]:
np.expand_dims(arr , axis=0) # increse the dimension by 1 at provided axis

array([[1, 2, 3, 4]])

In [11]:
np.expand_dims(arr , axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
np.expand_dims(arr , axis=1).ndim

2

In [13]:
arr

array([1, 2, 3, 4])

In [14]:
arr = np.zeros((3,4))

In [15]:
arr.ndim

2

In [16]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
np.expand_dims(arr, axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [18]:
np.expand_dims(arr, axis=0).ndim

3

In [19]:
a = np.array([[1],[2],[3],[4]])
a.ndim

2

In [ ]:
np.squeeze(a) # Remove axes of length one from a.

array([1, 2, 3, 4])

In [23]:
arr1

array([[2, 1, 1],
       [2, 2, 1],
       [1, 2, 2]])

In [24]:
np.repeat(arr1, 2)

array([2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2])

In [26]:
np.repeat(arr1, 2, axis=0)

array([[2, 1, 1],
       [2, 1, 1],
       [2, 2, 1],
       [2, 2, 1],
       [1, 2, 2],
       [1, 2, 2]])

In [28]:
a

array([[1],
       [2],
       [3],
       [4]])

In [29]:
np.roll(a, -2)

array([[3],
       [4],
       [1],
       [2]])

In [30]:
c = np.array([[1,2],[3,4],[5,6],[7,8]])
c 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [34]:
np.roll(c, -2)

array([[3, 4],
       [5, 6],
       [7, 8],
       [1, 2]])

In [35]:
np.roll(c, -7)

array([[8, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [36]:
arr1

array([[2, 1, 1],
       [2, 2, 1],
       [1, 2, 2]])

In [40]:
arr2

array([[2, 1, 2],
       [1, 1, 1],
       [1, 2, 2]])

In [41]:
arr1 > arr2

array([[False,  True, False],
       [False,  True,  True],
       [ True, False, False]])

In [ ]:
~arr1 # ~ -> negation

array([[-2, -3, -3],
       [-2, -3, -3],
       [-3, -3, -3]])

In [43]:
# operation on numpy string array


In [44]:
d = np.array(["rail", "way"])

In [45]:
d

array(['rail', 'way'], dtype='<U4')

In [46]:
np.char.upper(d)

array(['RAIL', 'WAY'], dtype='<U4')

In [47]:
np.char.capitalize(d)

array(['Rail', 'Way'], dtype='<U4')

In [48]:
# mathematical finction

In [49]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [2, 2, 2]])

In [50]:
np.sin(arr1)

array([[0.84147098, 0.90929743, 0.90929743],
       [0.84147098, 0.90929743, 0.90929743],
       [0.90929743, 0.90929743, 0.90929743]])

In [51]:
np.tan(arr1)

array([[ 1.55740772, -2.18503986, -2.18503986],
       [ 1.55740772, -2.18503986, -2.18503986],
       [-2.18503986, -2.18503986, -2.18503986]])

In [52]:
np.power(arr1, 3)

array([[1, 8, 8],
       [1, 8, 8],
       [8, 8, 8]])

In [53]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [54]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.     , 0.30103, 0.30103],
       [0.30103, 0.30103, 0.30103]])

In [55]:
np.std(arr1)

np.float64(0.41573970964154905)

In [56]:
np.var(arr1)

np.float64(0.1728395061728395)

In [57]:
arr1 - arr2

array([[-1,  1,  0],
       [ 0,  1,  1],
       [ 1,  0,  0]])

In [58]:
np.subtract(arr1,arr2)

array([[-1,  1,  0],
       [ 0,  1,  1],
       [ 1,  0,  0]])

In [59]:
np.multiply(arr1,arr2)

array([[2, 2, 4],
       [1, 2, 2],
       [2, 4, 4]])

In [ ]:
np.mod(arr1,arr2) #return element wise remainder

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [61]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356]])

In [62]:
# sort search 

In [63]:
e = np.array([2,3,1,7,6])

In [64]:
e

array([2, 3, 1, 7, 6])

In [66]:
np.sort(e)

array([1, 2, 3, 6, 7])

In [67]:
f = np.array([12,32,446,64,654,987,6532])

In [68]:
np.sort(f)

array([  12,   32,   64,  446,  654,  987, 6532])

In [69]:
np.searchsorted(f, 129) #Find indices where elements should be inserted to maintain order.

np.int64(4)

In [70]:
f = np.array([12,32,446,64,654,987,6532,0,0,0,4])

In [71]:
np.count_nonzero(f)

np.int64(8)

In [72]:
f>0

array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False,  True])

In [73]:
f[f>0]

array([  12,   32,  446,   64,  654,  987, 6532,    4])

In [74]:
f.byteswap()

array([  864691128455135232,  2305843009213693952, -4755519731526533120,
        4611686018427387904, -8214002770370363392, -2665286554473201664,
       -8928104786285297664,                    0,                    0,
                          0,   288230376151711744])

In [75]:
# matrix >> 2d array

In [76]:
import numpy.matlib as nm

In [77]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [79]:
nm.ones((5,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [90]:
# numpy linear algebra

arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,3))

In [91]:
arr1

array([[4, 7, 4],
       [3, 8, 4],
       [4, 1, 4]])

In [92]:
arr2

array([[6, 1, 6],
       [2, 9, 7],
       [9, 1, 7]])

In [93]:
arr1 @ arr2

array([[ 74,  71, 101],
       [ 70,  79, 102],
       [ 62,  17,  59]])

In [94]:
arr1

array([[4, 7, 4],
       [3, 8, 4],
       [4, 1, 4]])

In [95]:
np.linalg.det(arr1)

np.float64(23.999999999999993)

In [96]:
np.linalg.inv(arr1)

array([[ 1.16666667, -1.        , -0.16666667],
       [ 0.16666667, -0.        , -0.16666667],
       [-1.20833333,  1.        ,  0.45833333]])

In [102]:

# Question
# x+2y+3z=12 , 3.4x+5.7y+8z=3 , 4x+9y+16z=4
# find x,y,z

In [ ]:
a = np.array([[1,2,3],[3.4,5.7,8],[4,9,16]])

In [98]:
a

array([[ 1. ,  2. ,  3. ],
       [ 3.4,  5.7,  8. ],
       [ 4. ,  9. , 16. ]])

In [99]:
b = np.array([12,3,4])

In [100]:
b

array([12,  3,  4])

In [101]:
np.linalg.solve(a,b)

array([-95.90909091, 112.72727273, -39.18181818])

In [103]:
# answer is x=-95.90909091 , y=112.72727273, z=-39.18181818