In [ ]:
# Numpy >> numerical python
#2005 by travis Oliphant 

In [7]:
import numpy as np

In [5]:
np.__version__

'2.4.4'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
lis = [1,2,"Raghav",3+4j,1.2,True]

In [5]:
type(lis)

list

In [6]:
lis

[1, 2, 'Raghav', (3+4j), 1.2, True]

In [7]:
# Numpy store the data in an array
# An array is a container used to store the data of same data type

In [8]:
# why numpy
# computation is fast >> due to array >> continous memory location
# mathematical computaion

In [15]:
l = [1,2,3,4,5]
arr = np.array(l)

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
l = [1,2,3,4,5.2]
arr = np.array(l)

In [ ]:
arr 

array([1. , 2. , 3. , 4. , 5.2])

In [19]:
l = [1,2,3,4,5.2,"KK"]
arr = np.array(l)

In [20]:
arr

array(['1', '2', '3', '4', '5.2', 'KK'], dtype='<U32')

In [21]:
# arr stores homogenous data

In [22]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim # dimension of array

1

In [24]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [25]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr1.ndim

2

In [27]:
mat = np.matrix([1,2,3]) # matrix is a specialised array, 2 dimensional

In [28]:
type(mat)

numpy.matrix

In [29]:
np.matrix([[[1,2],[3,4],[5,6]]])

ValueError: matrix must be 2-dimensional

In [ ]:
# more way to convert array
l = [1,2,3,4]
np.asarray(l)

array([1, 2, 3, 4])

In [31]:
mat

matrix([[1, 2, 3]])

In [32]:
np.asarray(mat)

array([[1, 2, 3]])

In [33]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
np.asanyarray(mat) # it only convert those subclass into array which is not in array, but if something is already in it do not do any thing.

matrix([[1, 2, 3]])

In [1]:
t = ([1,2,3],[4,5,6]) #tuple in array


In [2]:
type(t)

tuple

In [6]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
l = [1,2,3,4,5]
arr = np.array(l)

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr[0] = 500

In [11]:
arr

array([500,   2,   3,   4,   5])

In [12]:
a = arr

In [13]:
a

array([500,   2,   3,   4,   5])

In [14]:
arr[0] = 1000

In [ ]:
a # change in array also lead to change in a >> shallow copy 

array([1000,    2,    3,    4,    5])

In [16]:
a = arr.copy()

In [17]:
a

array([1000,    2,    3,    4,    5])

In [18]:
arr[0] = 2000

In [19]:
arr

array([2000,    2,    3,    4,    5])

In [ ]:
a # deep copy

array([1000,    2,    3,    4,    5])

In [21]:
# multiple way to generate array 

In [24]:
arr1 = np.fromfunction(lambda i,j: i==j,(3,3)) #Construct an array by executing a function over each coordinate.

In [25]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
arr.ndim

1

In [ ]:
arr1.shape # shape of array

(3, 3)

In [ ]:
arr1.size #no. of elements in array

9

In [29]:
arr2 = np.fromfunction(lambda i,j: i*j,(3,3))

In [30]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [1]:
for i in range(5):
    print(i)

0
1
2
3
4


In [2]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [3]:
(i for i in range(5))

<generator object <genexpr> at 0x10d1b5560>

In [4]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [5]:
iterable = (i for i in range(5))

In [ ]:
np.fromiter(iterable, int) # create a new 1-d array from an iterable object.

array([0, 1, 2, 3, 4])

In [9]:
np.fromstring('22 23 34', sep=" ") #value should be numerical

array([22., 23., 34.])

In [10]:
np.fromstring('22,23,34', sep=",")

array([22., 23., 34.])

In [11]:
#for string character you have  to use split
string = 'Abhay, Raghav, Raghu'
string1 = string.split(',')
np.array(string1)

array(['Abhay', ' Raghav', ' Raghu'], dtype='<U7')

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
range(10)

range(0, 10)

In [ ]:
#other method of numpy >> to generate sequnce of nos
np.arange(1, 10, 0.1) # Return evenly spaced values within a given interval.

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [15]:
np.linspace(1, 5, 10) #Return evenly spaced numbers over a specified interval.
#give me 10 nos b/w 1 to 5 evenly spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.logspace(1,5,10) #Return numbers spaced evenly on a log scale. , base is 10
# 1  -> start, 5 -> end , 10 -> total number we want , [note : if you do not give base value then it assume base 10 ]

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [17]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])